### ISSUE TITLE
command line arguments ignored for Example_get_apr

### ISSUE THREAD

**Issue by krzysg** [cheesema/LibAPR#58]
when used with head.tif (it does not happen always). Command line to reproduce:
Example_get_apr -i head.tif -rel_error 0.01

Obviously it is overwritten by this code in auto_parameters(...):
https://github.com/cheesema/LibAPR/blob/2dddea899c668e12c770d1473c2fb4d95c0955be/src/algorithm/APRConverter.hpp#L563-L574

Before naive fix I think we need to discuss how to handle auto_parameters:
- should they be turned off when user provide *any* parameter like error/threshold etc.
- should they change only not provided (will it work correctly?)
- any other approach? like command line flag to actually *use* auto parameters explicitly?

**Comment by cheesema** [comment]
Good idea, lets discuss this tomorrow

**Comment by cheesema** [comment]
This should be resolved now with latest pull request. #76
