### ISSUE TITLE
After latest fix pipeline test with GCC is not passing

### ISSUE THREAD

**Issue by krzysg** [cheesema/LibAPR#63]
Fix introduced here: https://github.com/cheesema/LibAPR/commit/7053d6da340de37525351907b4212e8e61e98eb8 broke something.
On a master branch before fix everything works fine.

When run with clang:
```
cmake -DAPR_TESTS=ON ..
make -j 7 testAPR ; ./test/testAPR
```
everything is fine:
```
[----------] 4 tests from CreateSmallSphereTest (624 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (625 ms total)
[  PASSED  ] 4 tests.
```

but when running same stuff with GCC:
```
CC="gcc-7" CXX="g++-7" cmake -DAPR_TESTS=ON ..
make -j 7 testAPR ; ./test/testAPR
```

It fails:
```
[==========] 4 tests from 1 test case ran. (790 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CreateSmallSphereTest.APR_PIPELINE

 1 FAILED TEST
```

**Comment by cheesema** [comment]
Yip, makes sense, will check and fix tomorrow. Wasn't thinking... will need to double check, then update the test files. Also think on some further tests, to avoid other potential errors like this in the future.

**Comment by cheesema** [comment]
Hdf5 data type issue again, resolved.
