### ISSUE TITLE
force_load not supported on MS architectures

### ISSUE THREAD

**Issue by emmenlau** [cheesema/LibAPR#71]
When building the latest head on MSVC 2017, I get errors:
```
LINK : warning LNK4044: unrecognized option '/Wl,-force_load,D:/tmp-debug-MSVC-Generic-7-x64-cl19.11.25547/LibAPR/external/c-blosc/blosc/libblosc.lib'; ignored
   Creating library apr.lib and object apr.exp
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_compress referenced in function blosc_filter
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_decompress referenced in function blosc_filter
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_set_compressor referenced in function blosc_filter
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_compcode_to_compname referenced in function blosc_filter
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_list_compressors referenced in function blosc_filter
blosc_filter.c.obj : error LNK2019: unresolved external symbol blosc_cbuffer_sizes referenced in function blosc_filter
apr.dll : fatal error LNK1120: 6 unresolved externals
```

Is it correct that linker option `force_load` is not supported on MS architectures? I found https://stackoverflow.com/questions/25038974/force-load-linker-flag-for-other-platforms

**Comment by skalarproduktraum** [comment]
Hi @emmenlau,

are you using the Microsoft compiler in VS2017? We currently do not support it because it either does not support some options, or produces crashing code. It works though with the Intel compiler, if you'd like to try that.

**Comment by emmenlau** [comment]
Hi @skalarproduktraum , I'm using various compilers to test code quality. There is MacOSX clang, various versions of gcc on Linux, gcc on MS Windows (MinGW64), and MSVC 2015 and 2017.
I currently do not use the Intel compiler.

Are you planning to support MSVC compiler in the future?

Most issues I have fixed in the PR are according to the C/C++ standard, so they are not platform-specific. For example including <algorithm> for min/max should be correct on all platforms, even though not all compilers _require_ it. Not all compilers require them, but for correctness you may add them on all platforms. The only exception is the definition of `M_PI` that AFAIK is only required on MSVC.

**Comment by skalarproduktraum** [comment]
Ah, sorry, I hadn't seen your PR! Thanks!

We do plan to support MSVC at some point in the future, we just don't have the resources to do the required fixes and testing at the moment.

**Comment by emmenlau** [comment]
Ok great! If you allow I'd like to continue contributing testing and minor fixes?

**Comment by skalarproduktraum** [comment]
Of course! We're happily taking PRs :) Thank you for your time and effort! 👍

**Comment by emmenlau** [comment]
Great! I have not looked into `force_load` yet because I did not know this option before, but I'll fix it when I get around to it. Maybe lets leave this issue open in case someone beats me to it :-) Thanks for your nice work!

**Comment by emmenlau** [comment]
@skalarproduktraum it seems still a bit "experimental", see i.e. https://gitlab.kitware.com/cmake/cmake/issues/16730. If it fails to build my standard set of prerequisites, I'd be tempted not to invest too much time to get it working.

Can you elaborate what problems you're facing with MSVC? Did you try 2017? I'm certainly no fan of the Microsoft compiler! But there are reasonable efforts from Microsoft underway to get a critical mass of standard thirdparty sources built on Windows, see https://github.com/Microsoft/vcpkg

At least it might be worthwhile to get LibAPR build with MSVC, so people can perform testing and provide more feedback?

**Comment by skalarproduktraum** [comment]
@emmenlau building works with MSVC 2017 (at least), but the generated binaries don't work, and crash in rather random places. Also, MSVC still only supports OpenMP 2.0, while we require 3.x, and that would make MSVC-built binaries also quite slow. As said, with VS+Intel compiler it works, but it's a bit of a heavy prerequisite that also requires its own runtime libraries...

**Comment by skalarproduktraum** [comment]
OpenMP can be disabled by passing `-DDISABLE_OPENMP=1` to CMake.

Regarding your currently open PR: Is this all you want to add for the moment? Then we'd have a look and check. 

Msys2: Yes, I know it's quite nice, but the problem (and please correct me if this is not true anymore) is an ABI that is incompatible with MSVC, so msys2/mingw64-built stuff cannot be linked into a MSVC executable/library, which is quite a dealbreaker. Yeah, and if clang doesn't work well, then don't pursue that further. Let's see what we can get out with MSVC.

**Comment by emmenlau** [comment]
Regarding the PR, if you can already merge it then please go ahead, it would add some helpful details. I've just pushed another minor change that enables successful building with MinGW64 on MSYS2, so it does add value in itself. The MSVC build is not complete which takes away a bit of value from the PR, but on the other hand, the PR adds only changes that are true code improvements for all platforms, so it should not hurt in any case.

MSYS2: yes, the ABI is incompatible. Its really mostly useful as long as the full executable is built in MinGW-land. But I think it finds quite a user base nowadays...

**Comment by emmenlau** [comment]
Can I re-phrase part of my question? Why is blosc required to be static in the current build?

I have switched to external blosc (see https://github.com/cheesema/LibAPR/pull/75) and at least the build of LibAPR seems fine. Did you encounter problems with dynamically linked blosc? It seems a bit cleaner to build blosc static or dynamic based on LibAPR, not mix two styles?

Thanks for your input!

**Comment by krzysg** [comment]
The idea behind static blosc is that it can be easily link to both - static and shared LibAPR - to produce fat libs. Then in installation step we just need to isntall libapr.dylib (or .so), libapr.a and LibAPR header files.

**Comment by emmenlau** [comment]
Ok, then in my eyes, the issue can be closed. With the PR https://github.com/cheesema/LibAPR/pull/75 I can use an external dynamic c-blosc, and force_load is not a problem anymore.

**Comment by krzysg** [comment]
It should work now, I have merge some changes made in CMakeLists.txt during hackathon. Seems that force_load is supported only on Apple platfrom (by both - clang and gcc). On Linux and probably Windows (I have no way to check it) "--whole-archive" should be used (and whole-archive is not supported on Apple...). It is now pushed on 'develop' branch.
