### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by skalarproduktraum** [cheesema/LibAPR#72]
We'd like to run our tests in an automated fashion, so it'd be nice to set up Travis at some point.

**Comment by MSusik** [comment]
Hi!

I started with dockerizing the application, as I has a lot of problems with installation. You can check progress here: https://github.com/MSusik/libaprdocker

I still can't get through the CMake installation.

The first error I got is about this line:
```project(LibAPR DESCRIPTION "Adaptive Particle Representation library") ```
Simply removing ```DESCRIPTION "Adaptive Particle Representation library``` does the trick here.

Then, I'm stuck with c-blosc
```
CMake Error at CMakeLists.txt:68 (add_subdirectory):
  The source directory

    /srv/LibAPR/external/c-blosc

  does not contain a CMakeLists.txt file.
```

If you could check what I'm doing wrong, then I could progress with Docker and CI.

Thanks!

**Comment by MSusik** [comment]
I believe this might be helpful https://github.com/cheesema/LibAPR/pull/75

**Comment by krzysg** [comment]
Please use at least cmake 3.9 (DESCRIPTION is not supported earlier). Problem here is that CMakeLists.txt does not require such high revision - it will be udpated soon and probably required version will be 3.10 since it introduce nice features for CUDA and  I guess this is what currently will be needed in LibAPR.

Regarding your blosc problem please clone it with recursive flag:
```
git clone --recursive git@github.com:cheesema/LibAPR.git
```

or after cloning main repository run:
```
git submodule update --init --recursive
```

**Comment by psteinb** [comment]
I agree as discussed last week. Let's bump the minimum required cmake 
version then.

**Comment by MSusik** [comment]
All right, https://github.com/MSusik/libaprdocker contains a working Docker recipe.

I prefer to keep Dockerfile on a separate repository, if it is not intended to be used in development.

Please tell me, what can be checked during a Travis build? How to run tests?

Thanks!

**Comment by cheesema** [comment]
I'll talk to the boys tomorrow re this.

**Comment by cheesema** [comment]
So we are a step closer, build integration is done, we just need to get the tests integrated.

**Comment by MSusik** [comment]
Seems that it is done https://travis-ci.org/cheesema/LibAPR.

@krzysg I'm closing the issue, feel free to reopen if there is anything to add.
