### ISSUE TITLE
Namechange MeshData -> PixelData

### ISSUE THREAD

**Issue by cheesema** [cheesema/LibAPR#82]
What do you guys think @skalarproduktraum this would make you happy?

@krzysg ?

**Comment by krzysg** [comment]
Do we need that change? I mean, I do not have any objections to change it - if this is MeshData, PixelData or even GridData it's completely OK for me. (It can be even IdoNotGiveAShitAboutPixelDataSinceIuseApr class ;-) ).

**Comment by cheesema** [comment]
hahahaha, yeah this is more of a response to Ulriks dislike + it woudl also align with the language we use in the paper, and avoid any ambiguity.

**Comment by skalarproduktraum** [comment]
Go for PixelData. It _is_ pixel data you're representing and therefore the least confusing naming for external people 👍

**Comment by krzysg** [comment]
Everything seems to work fine after changes so closing.
